name: ec2_aws_deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug EC2_HOST
      run: echo "EC_HOST is ${{ secrets.EC2_HOST }}"

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Copy project to EC2
      run: |
        rsync -avz -e "ssh -i ~/.ssh/id_rsa" . ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST}}:/home/ubuntu/crew-station-back

    - name: Build & Run Docker on EC2
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST}} << EOF
          cd /home/ubuntu/crew-station-back
          docker stop crew-station-back || true
          docker rm crew-station-back || true
          docker rmi crew-station-back || true
          docker build --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
            --build-arg EC2_HOST=${{ secrets.EC2_HOST }} \
            --build-arg EC2_DATABASE_HOST=${{ secrets.EC2_DATABASE_HOST }} \
            --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            --build-arg AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }} \
            --build-arg AWS_REGION=${{ secrets.AWS_REGION }} \
            --build-arg KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }} \
            --build-arg KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }} \
            --build-arg NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }} \
            --build-arg NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }} \
            --build-arg SMS_ACCESS_KEY=${{ secrets.SMS_ACCESS_KEY }} \
            --build-arg SMS_SECRET_ACCESS_KEY=${{ secrets.SMS_SECRET_ACCESS_KEY }} \
          -t crew-station-back .
          docker run -d -p 80:10000 --name crew-station-back \
            -e EC2_HOST=${{ secrets.EC2_HOST }} \
            -e EC2_DATABASE_HOST=${{ secrets.EC2_DATABASE_HOST }} \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }} \
            -e AWS_REGION=${{ secrets.AWS_REGION }} \
            -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            -e GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
            -e KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }} \
            -e KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }} \
            -e NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }} \
            -e NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }} \
            -e SMS_ACCESS_KEY=${{ secrets.SMS_ACCESS_KEY }} \
            -e SMS_SECRET_ACCESS_KEY=${{ secrets.SMS_SECRET_ACCESS_KEY }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            crew-station-back
            
    - name: Clean up not used images
      if: success()
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST}} << 'EOF'
          docker image prune -f
          docker container prune -f
